### ISSUE TITLE
Conflicting path for interface bind-ni-name

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-base-model#26]
This issue references the dell-interface.yang model.

The bind-ni-name field (Network Instance to which an interface is bound) has the following path:
`if/interfaces-state/interface/bind-ni-name`. See it in the file [here](https://github.com/open-switch/opx-base-model/blob/master/yang-models/dell-interface.yang#L462).

However, the script which implements the configuration of network instances references a different path for this field: `if/interfaces/interface/bind-ni-name`.  See it in the file [here](https://github.com/open-switch/opx-nas-linux/blob/master/scripts/bin/base_vrf.py#L105).
Note `interfaces` instead of `interfaces-state`.

`if/interfaces/interface/bind-ni-name` is missing from the YANG model in dell-interface.yang

**Comment by jeff-yin** [comment]
@GarrickHe Can you take a look at this one? Check with @rakeshdatta if you need advice.

**Comment by GarrickHe** [comment]
@jeff-yin @james-jra 
I'll look into this.

**Comment by rakeshdatta** [comment]
Hi @james-jra , @GarrickHe ,

I took a look quickly.

bind-ni-name is present in 'interface-state/interface' as well as 'interfaces/interface'.

'ni/if/interfaces/interface/bind-ni-name' refers to :  https://github.com/open-switch/opx-base-model/blob/master/rfc/ietf-network-instance.yang#L147.

Plz let us know if you're having any behavior issue due to this.

**Comment by james-jra** [comment]
@rakeshdatta 

Sorry, I didn't find that before, thank you for pointing it out
There is no behaviour issue.

I'm happy to close this issue
